name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        ./.github/scripts/install_dependencies.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --workspace --all-features --all-targets --verbose
    - name: Build docs
      run: cargo doc --no-deps
